spring:
  datasource:
    url: jdbc:mysql://localhost:3307/billingwise?useSSL=false&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1004
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: validate
    generate-ddl: false
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
app:
  auth:
    token:
      secret-key: zhtkgytjdqlfflddhkdlwm