spring:
  datasource:
    primary:
      jdbc-url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    replica:
      jdbc-url: ${DB_REPLICA_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100

  flyway:
    url: ${spring.datasource.primary.jdbc-url}
    user: ${spring.datasource.primary.username}
    password: ${spring.datasource.primary.password}
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
app:
  auth:
    token:
      secret-key: ${JWT_SECRET_KEY}

front:
  url: https://www.billingwise.site/