server:
  port: 8081

spring:
  profiles:
    active: dev

#aws:
#  s3:
#    access-key: ${AWS_S3_ACCESS_KEY}
#    secret-key: ${AWS_S3_SECRET_KEY}
#    region: ${AWS_S3_REGION}
#    bucket: ${AWS_S3_BUCKET}

logging:
  level:
    org:
      hibernate: info