== 계약 API
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:seclinks:

계약 관련 API입니다.

=== 계약 생성

계약을 생성합니다.

operation::contract/create[snippets='request-cookies,http-request,request-fields,http-response']


=== 계약 수정

계약 정보를 수정합니다.

operation::contract/edit[snippets='request-cookies,http-request,path-parameters,request-fields,http-response']


=== 계약 삭제

계약 정보를 삭제합니다.

operation::contract/delete[snippets='request-cookies,http-request,path-parameters,http-response']


=== 계약 상세 조회

계약 상세 정보를 조회합니다.

operation::contract/get[snippets='request-cookies,http-request,path-parameters,http-response,response-fields']


=== 계약 목록 조회

계약 목록의 조회합니다

operation::contract/get-list[snippets='request-cookies,http-request,http-response,response-fields']\


=== 계약 대량 등록

엑셀 파일을 활용하여 계약 정보를 대량 등록합니다.

operation::contract/bulk-register/success[snippets='request-cookies,http-request,http-response,response-fields']
operation::contract/bulk-register/fail[snippets='http-response,response-fields']